ktor {
  deployment {
    port = 8080
    port = ${?PORT}
    host = "0.0.0.0"
    requestQueueLimit = 16
  }
  application {
    modules = [ com.example.scheduler.ApplicationKt.module ]
  }
}

scheduling {
  intervalMs = 60000
  batchLimit = 20
}

firebase {
  projectId = "complete-octane-470215-f6"
}
