-- POSHMA RDBMS Schema (Oracle Database 21c compatible)
-- Booleans direpresentasikan dengan CHAR(1) menggunakan nilai 'Y'/'N'.

-------------------------------------------------------------------------------
-- MASTER DATA
-------------------------------------------------------------------------------

CREATE TABLE roles (
    role_id    NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_code  VARCHAR2(30) NOT NULL,
    role_name  VARCHAR2(100) NOT NULL,
    CONSTRAINT roles_pk PRIMARY KEY (role_id),
    CONSTRAINT roles_code_uk UNIQUE (role_code)
);

CREATE TABLE outlets (
    outlet_id  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code       VARCHAR2(20) NOT NULL,
    name       VARCHAR2(150) NOT NULL,
    address    CLOB,
    phone      VARCHAR2(30),
    is_active  CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT outlets_pk PRIMARY KEY (outlet_id),
    CONSTRAINT outlets_code_uk UNIQUE (code)
);

CREATE TABLE users (
    user_id        NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id      NUMBER(19),
    role_id        NUMBER(6) NOT NULL,
    full_name      VARCHAR2(150) NOT NULL,
    email          VARCHAR2(150) NOT NULL,
    password_hash  VARCHAR2(255) NOT NULL,
    phone          VARCHAR2(30),
    is_active      CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    last_login_at  TIMESTAMP,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (user_id),
    CONSTRAINT users_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT users_role_fk FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT users_outlet_email_uk UNIQUE (outlet_id, email)
);

CREATE TABLE categories (
    category_id  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id    NUMBER(19) NOT NULL,
    name         VARCHAR2(120) NOT NULL,
    slug         VARCHAR2(120),
    applies_to   VARCHAR2(10) DEFAULT 'goods' CHECK (applies_to IN ('goods', 'service', 'both')),
    is_active    CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    sort_order   NUMBER(10) DEFAULT 0,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    CONSTRAINT categories_pk PRIMARY KEY (category_id),
    CONSTRAINT categories_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT categories_outlet_name_uk UNIQUE (outlet_id, name),
    CONSTRAINT categories_outlet_slug_uk UNIQUE (outlet_id, slug)
);

CREATE TABLE suppliers (
    supplier_id       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id         NUMBER(19) NOT NULL,
    name              VARCHAR2(180) NOT NULL,
    phone             VARCHAR2(30),
    email             VARCHAR2(150),
    address           CLOB,
    is_active         CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    payment_term_days NUMBER(10) DEFAULT 0,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT suppliers_pk PRIMARY KEY (supplier_id),
    CONSTRAINT suppliers_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT suppliers_outlet_name_uk UNIQUE (outlet_id, name)
);

CREATE TABLE products (
    product_id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id             NUMBER(19) NOT NULL,
    category_id           NUMBER(19),
    default_supplier_id   NUMBER(19),
    sku                   VARCHAR2(60) NOT NULL,
    name                  VARCHAR2(200) NOT NULL,
    type                  VARCHAR2(10) NOT NULL CHECK (type IN ('goods', 'service')),
    track_stock           CHAR(1) DEFAULT 'Y' CHECK (track_stock IN ('Y', 'N')),
    stock_qty             NUMBER(18, 2) DEFAULT 0,
    reorder_point         NUMBER(18, 2),
    last_cost             NUMBER(18, 2) DEFAULT 0,
    sale_price            NUMBER(18, 2) DEFAULT 0,
    staged_sale_price     NUMBER(18, 2),
    staged_last_cost      NUMBER(18, 2),
    staged_incoming_qty   NUMBER(18, 2),
    staged_old_qty        NUMBER(18, 2),
    is_active             CHAR(1) DEFAULT 'Y' CHECK (is_active IN ('Y', 'N')),
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,
    CONSTRAINT products_pk PRIMARY KEY (product_id),
    CONSTRAINT products_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT products_supplier_fk FOREIGN KEY (default_supplier_id) REFERENCES suppliers (supplier_id),
    CONSTRAINT products_outlet_sku_uk UNIQUE (outlet_id, sku),
    CONSTRAINT products_outlet_name_uk UNIQUE (outlet_id, name)
);

CREATE TABLE product_images (
    product_image_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_id       NUMBER(19) NOT NULL,
    image_url        CLOB NOT NULL,
    sort_order       NUMBER(10) DEFAULT 0,
    uploaded_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT product_images_pk PRIMARY KEY (product_image_id),
    CONSTRAINT product_images_product_fk FOREIGN KEY (product_id)
        REFERENCES products (product_id) ON DELETE CASCADE
);

CREATE TABLE product_suppliers (
    product_id  NUMBER(19) NOT NULL,
    supplier_id NUMBER(19) NOT NULL,
    is_primary  CHAR(1) DEFAULT 'N' CHECK (is_primary IN ('Y', 'N')),
    note        CLOB,
    CONSTRAINT product_suppliers_pk PRIMARY KEY (product_id, supplier_id),
    CONSTRAINT product_suppliers_product_fk FOREIGN KEY (product_id)
        REFERENCES products (product_id) ON DELETE CASCADE,
    CONSTRAINT product_suppliers_supplier_fk FOREIGN KEY (supplier_id)
        REFERENCES suppliers (supplier_id) ON DELETE CASCADE
);

CREATE TABLE document_counters (
    counter_id  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id   NUMBER(19) NOT NULL,
    doc_type    VARCHAR2(30) NOT NULL,
    period      DATE NOT NULL,
    last_number NUMBER(10) DEFAULT 0,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT document_counters_pk PRIMARY KEY (counter_id),
    CONSTRAINT document_counters_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT document_counters_uk UNIQUE (outlet_id, doc_type, period)
);

-------------------------------------------------------------------------------
-- PURCHASING & INBOUND
-------------------------------------------------------------------------------

CREATE TABLE purchases (
    purchase_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id      NUMBER(19) NOT NULL,
    supplier_id    NUMBER(19),
    created_by     NUMBER(19),
    invoice_no     VARCHAR2(50),
    status         VARCHAR2(15) NOT NULL CHECK (status IN ('DRAFT', 'ORDERED', 'RECEIVED', 'CANCELLED')),
    payment_status VARCHAR2(15) NOT NULL CHECK (payment_status IN ('UNPAID', 'PARTIAL', 'PAID')),
    ordered_at     TIMESTAMP,
    received_at    TIMESTAMP,
    due_date       DATE,
    term_days      NUMBER(10),
    notes          CLOB,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT purchases_pk PRIMARY KEY (purchase_id),
    CONSTRAINT purchases_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT purchases_supplier_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id),
    CONSTRAINT purchases_user_fk FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE TABLE purchase_items (
    purchase_item_id     NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    purchase_id          NUMBER(19) NOT NULL,
    product_id           NUMBER(19) NOT NULL,
    ordered_qty          NUMBER(18, 2) NOT NULL,
    received_qty         NUMBER(18, 2) DEFAULT 0,
    unit_cost            NUMBER(18, 2) NOT NULL,
    suggested_sale_price NUMBER(18, 2),
    remarks              CLOB,
    CONSTRAINT purchase_items_pk PRIMARY KEY (purchase_item_id),
    CONSTRAINT purchase_items_purchase_fk FOREIGN KEY (purchase_id)
        REFERENCES purchases (purchase_id) ON DELETE CASCADE,
    CONSTRAINT purchase_items_product_fk FOREIGN KEY (product_id)
        REFERENCES products (product_id)
);

CREATE TABLE stock_batches (
    stock_batch_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id         NUMBER(19) NOT NULL,
    product_id        NUMBER(19) NOT NULL,
    purchase_item_id  NUMBER(19),
    supplier_id       NUMBER(19),
    invoice_no        VARCHAR2(50),
    unit_cost         NUMBER(18, 2) NOT NULL,
    sale_price        NUMBER(18, 2),
    received_qty      NUMBER(18, 2) NOT NULL,
    remaining_qty     NUMBER(18, 2) NOT NULL,
    received_at       TIMESTAMP NOT NULL,
    due_date          DATE,
    term_days         NUMBER(10),
    state             VARCHAR2(15) NOT NULL CHECK (state IN ('HOLD', 'OPEN', 'CLEARED')),
    activated_at      TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_batches_pk PRIMARY KEY (stock_batch_id),
    CONSTRAINT stock_batches_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT stock_batches_product_fk FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT stock_batches_purchase_item_fk FOREIGN KEY (purchase_item_id) REFERENCES purchase_items (purchase_item_id),
    CONSTRAINT stock_batches_supplier_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id)
);

CREATE TABLE pending_stock_receipts (
    pending_receipt_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id          NUMBER(19) NOT NULL,
    product_id         NUMBER(19) NOT NULL,
    supplier_id        NUMBER(19),
    purchase_id        NUMBER(19),
    invoice_no         VARCHAR2(50),
    qty                NUMBER(18, 2) NOT NULL,
    unit_cost          NUMBER(18, 2) NOT NULL,
    new_sale_price     NUMBER(18, 2),
    status             VARCHAR2(15) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'POSTED', 'CANCELLED')),
    held               CHAR(1) DEFAULT 'N' CHECK (held IN ('Y', 'N')),
    notification_sent  CHAR(1) DEFAULT 'N' CHECK (notification_sent IN ('Y', 'N')),
    term_days          NUMBER(10),
    due_date           DATE,
    scheduled_at       TIMESTAMP,
    created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    processing_at      TIMESTAMP,
    posted_at          TIMESTAMP,
    CONSTRAINT pending_receipts_pk PRIMARY KEY (pending_receipt_id),
    CONSTRAINT pending_receipts_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT pending_receipts_product_fk FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT pending_receipts_supplier_fk FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id),
    CONSTRAINT pending_receipts_purchase_fk FOREIGN KEY (purchase_id) REFERENCES purchases (purchase_id)
);

-------------------------------------------------------------------------------
-- SALES
-------------------------------------------------------------------------------

CREATE TABLE sales (
    sale_id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id         NUMBER(19) NOT NULL,
    sale_number       VARCHAR2(30) NOT NULL,
    cashier_id        NUMBER(19) NOT NULL,
    customer_name     VARCHAR2(150),
    subtotal          NUMBER(18, 2) DEFAULT 0,
    service_fee       NUMBER(18, 2) DEFAULT 0,
    service_description VARCHAR2(200),
    discount_amount   NUMBER(18, 2) DEFAULT 0,
    total_amount      NUMBER(18, 2) NOT NULL,
    paid_amount       NUMBER(18, 2) NOT NULL,
    change_amount     NUMBER(18, 2) DEFAULT 0,
    payment_status    VARCHAR2(15) NOT NULL CHECK (payment_status IN ('PENDING', 'PAID', 'VOID')),
    payment_method    VARCHAR2(15) NOT NULL CHECK (payment_method IN ('CASH', 'TRANSFER', 'QRIS', 'MIXED')),
    notes             CLOB,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paid_at           TIMESTAMP,
    voided_at         TIMESTAMP,
    CONSTRAINT sales_pk PRIMARY KEY (sale_id),
    CONSTRAINT sales_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT sales_cashier_fk FOREIGN KEY (cashier_id) REFERENCES users (user_id),
    CONSTRAINT sales_outlet_number_uk UNIQUE (outlet_id, sale_number)
);

CREATE TABLE sale_items (
    sale_item_id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sale_id        NUMBER(19) NOT NULL,
    product_id     NUMBER(19) NOT NULL,
    stock_batch_id NUMBER(19),
    quantity       NUMBER(18, 2) NOT NULL,
    unit_price     NUMBER(18, 2) NOT NULL,
    discount_amount NUMBER(18, 2) DEFAULT 0,
    line_total     NUMBER(18, 2) NOT NULL,
    unit_cost      NUMBER(18, 2),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sale_items_pk PRIMARY KEY (sale_item_id),
    CONSTRAINT sale_items_sale_fk FOREIGN KEY (sale_id)
        REFERENCES sales (sale_id) ON DELETE CASCADE,
    CONSTRAINT sale_items_product_fk FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT sale_items_batch_fk FOREIGN KEY (stock_batch_id) REFERENCES stock_batches (stock_batch_id)
);

CREATE TABLE sale_payments (
    sale_payment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sale_id         NUMBER(19) NOT NULL,
    method          VARCHAR2(15) NOT NULL CHECK (method IN ('CASH', 'TRANSFER', 'QRIS')),
    amount          NUMBER(18, 2) NOT NULL,
    reference_no    VARCHAR2(50),
    paid_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sale_payments_pk PRIMARY KEY (sale_payment_id),
    CONSTRAINT sale_payments_sale_fk FOREIGN KEY (sale_id)
        REFERENCES sales (sale_id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- INVENTORY CONTROL
-------------------------------------------------------------------------------

CREATE TABLE stock_adjust_requests (
    adjust_request_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id         NUMBER(19) NOT NULL,
    product_id        NUMBER(19) NOT NULL,
    requested_by      NUMBER(19) NOT NULL,
    requested_delta   NUMBER(18, 2) NOT NULL,
    reason            CLOB,
    status            VARCHAR2(15) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    decided_by        NUMBER(19),
    decided_at        TIMESTAMP,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT stock_adjust_requests_pk PRIMARY KEY (adjust_request_id),
    CONSTRAINT stock_adjust_requests_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT stock_adjust_requests_product_fk FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT stock_adjust_requests_requester_fk FOREIGN KEY (requested_by) REFERENCES users (user_id),
    CONSTRAINT stock_adjust_requests_decider_fk FOREIGN KEY (decided_by) REFERENCES users (user_id)
);

CREATE TABLE inventory_movements (
    inventory_movement_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id             NUMBER(19) NOT NULL,
    product_id            NUMBER(19) NOT NULL,
    stock_batch_id        NUMBER(19),
    movement_type         VARCHAR2(15) NOT NULL CHECK (movement_type IN ('SALE', 'PURCHASE', 'ADJUSTMENT', 'TRANSFER', 'CORRECTION', 'OPENING')),
    quantity_delta        NUMBER(18, 2) NOT NULL,
    unit_cost             NUMBER(18, 2),
    reference_table       VARCHAR2(30),
    reference_id          NUMBER(19),
    note                  CLOB,
    created_by            NUMBER(19),
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT inventory_movements_pk PRIMARY KEY (inventory_movement_id),
    CONSTRAINT inventory_movements_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT inventory_movements_product_fk FOREIGN KEY (product_id) REFERENCES products (product_id),
    CONSTRAINT inventory_movements_batch_fk FOREIGN KEY (stock_batch_id) REFERENCES stock_batches (stock_batch_id),
    CONSTRAINT inventory_movements_user_fk FOREIGN KEY (created_by) REFERENCES users (user_id)
);

-------------------------------------------------------------------------------
-- NOTIFICATIONS
-------------------------------------------------------------------------------

CREATE TABLE notifications (
    notification_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    outlet_id       NUMBER(19),
    title           VARCHAR2(150) NOT NULL,
    body            CLOB,
    priority        VARCHAR2(10) DEFAULT 'NORMAL' CHECK (priority IN ('LOW', 'NORMAL', 'HIGH')),
    target_role_id  NUMBER(6),
    created_by      NUMBER(19),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pk PRIMARY KEY (notification_id),
    CONSTRAINT notifications_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets (outlet_id),
    CONSTRAINT notifications_role_fk FOREIGN KEY (target_role_id) REFERENCES roles (role_id),
    CONSTRAINT notifications_user_fk FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE TABLE notification_recipients (
    notification_id NUMBER(19) NOT NULL,
    user_id         NUMBER(19) NOT NULL,
    read_at         TIMESTAMP,
    CONSTRAINT notification_recipients_pk PRIMARY KEY (notification_id, user_id),
    CONSTRAINT notification_recipients_notification_fk FOREIGN KEY (notification_id)
        REFERENCES notifications (notification_id) ON DELETE CASCADE,
    CONSTRAINT notification_recipients_user_fk FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- INDEXES
-------------------------------------------------------------------------------

CREATE INDEX users_role_idx ON users (role_id);
CREATE INDEX products_category_idx ON products (category_id);
CREATE INDEX products_supplier_idx ON products (default_supplier_id);
CREATE INDEX products_name_search_idx ON products (outlet_id, LOWER(name));
CREATE INDEX purchase_items_product_idx ON purchase_items (product_id);
CREATE INDEX stock_batches_product_state_idx ON stock_batches (product_id, state);
CREATE INDEX sales_created_at_idx ON sales (created_at);
CREATE INDEX sale_items_product_idx ON sale_items (product_id);
CREATE INDEX inventory_movements_product_idx ON inventory_movements (product_id, movement_type, created_at);
CREATE INDEX stock_adjust_requests_status_idx ON stock_adjust_requests (status);

